<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Aturan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Aturan_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
    }

    public function index()
    {
        $this->render['content']   = $this->load->view('aturan/aturan_list',array(), TRUE);
        $this->load->view('template', $this->render);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Aturan_model->json();
    }

    public function read($id) 
    {
        $row = $this->Aturan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'parameter_1' => $row->parameter_1,
		'parameter_2' => $row->parameter_2,
		'hasil' => $row->hasil,
	    );
            $this->render['content']   = $this->load->view('aturan/aturan_read', $data, TRUE);
            $this->load->view('template', $this->render);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('aturan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('aturan/create_action'),
	    'id' => set_value('id'),
	    'parameter_1' => set_value('parameter_1'),
	    'parameter_2' => set_value('parameter_2'),
	    'hasil' => set_value('hasil'),
	);
        $this->render['content']   = $this->load->view('aturan/aturan_form', $data, TRUE);
        $this->load->view('template', $this->render);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'parameter_1' => $this->input->post('parameter_1',TRUE),
		'parameter_2' => $this->input->post('parameter_2',TRUE),
		'hasil' => $this->input->post('hasil',TRUE),
	    );

            $this->Aturan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('aturan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Aturan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('aturan/update_action'),
		'id' => set_value('id', $row->id),
		'parameter_1' => set_value('parameter_1', $row->parameter_1),
		'parameter_2' => set_value('parameter_2', $row->parameter_2),
		'hasil' => set_value('hasil', $row->hasil),
	    );
        $this->render['content']   = $this->load->view('aturan/aturan_form', $data, TRUE);
        $this->load->view('template', $this->render);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('aturan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'parameter_1' => $this->input->post('parameter_1',TRUE),
		'parameter_2' => $this->input->post('parameter_2',TRUE),
		'hasil' => $this->input->post('hasil',TRUE),
	    );

            $this->Aturan_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('aturan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Aturan_model->get_by_id($id);

        if ($row) {
            $this->Aturan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('aturan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('aturan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('parameter_1', 'parameter 1', 'trim|required');
	$this->form_validation->set_rules('parameter_2', 'parameter 2', 'trim|required');
	$this->form_validation->set_rules('hasil', 'hasil', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Aturan.php */
/* Location: ./application/controllers/Aturan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-13 15:56:07 */
/* http://harviacode.com */