<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Parameter extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Parameter_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->render['content']   = $this->load->view('parameter/parameter_list', array(), TRUE);
        $this->load->view('template', $this->render);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Parameter_model->json();
    }

    public function read($id) 
    {
        $row = $this->Parameter_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_jenis' => $row->id_jenis,
		'parameter' => $row->parameter,
	    );
            $this->render['content']   = $this->load->view('parameter/parameter_read', $data, TRUE);
            $this->load->view('template', $this->render);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('parameter'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('parameter/create_action'),
	    'id' => set_value('id'),
	    'id_jenis' => set_value('id_jenis'),
	    'parameter' => set_value('parameter'),
	);
        $this->render['content']   = $this->load->view('parameter/parameter_form', $data, TRUE);
        $this->load->view('template', $this->render);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_jenis' => $this->input->post('id_jenis',TRUE),
		'parameter' => $this->input->post('parameter',TRUE),
	    );

            $this->Parameter_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('parameter'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Parameter_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('parameter/update_action'),
		'id' => set_value('id', $row->id),
		'id_jenis' => set_value('id_jenis', $row->id_jenis),
		'parameter' => set_value('parameter', $row->parameter),
	    );
        $this->render['content']   = $this->load->view('parameter/parameter_form', $data, TRUE);
        $this->load->view('template', $this->render);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('parameter'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_jenis' => $this->input->post('id_jenis',TRUE),
		'parameter' => $this->input->post('parameter',TRUE),
	    );

            $this->Parameter_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('parameter'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Parameter_model->get_by_id($id);

        if ($row) {
            $this->Parameter_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('parameter'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('parameter'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_jenis', 'id jenis', 'trim|required');
	$this->form_validation->set_rules('parameter', 'parameter', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Parameter.php */
/* Location: ./application/controllers/Parameter.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-20 03:05:47 */
/* http://harviacode.com */