<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Detail_pesanan_model extends CI_Model
{

    public $table = 'detail_pesanan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('detail_pesanan.id,id_pesanan,nama,jumlah,total');
        $this->datatables->from('detail_pesanan');
        //add this line for join
        //$this->datatables->join('pesanan', 'detail_pesanan.id_pesanan = pesanan.id');
        $this->datatables->join('menu', 'detail_pesanan.id_menu = menu.id');
        $this->datatables->add_column('action', anchor(site_url('detail_pesanan/read/$1'),'Read')." | ".anchor(site_url('detail_pesanan/update/$1'),'Update')." | ".anchor(site_url('detail_pesanan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_pesanan', $q);
	$this->db->or_like('id_menu', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('total', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_pesanan', $q);
	$this->db->or_like('id_menu', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('total', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Detail_pesanan_model.php */
/* Location: ./application/models/Detail_pesanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-26 09:28:54 */
/* http://harviacode.com */