<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Menu_model extends CI_Model
{

    public $table = 'menu';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('jenis_menu.id,jenis,nama,img,harga');
        $this->datatables->from('menu');
        //add this line for join
        $this->datatables->join('jenis_menu', 'menu.id_jenis = jenis_menu.id');
        $this->datatables->add_column('action', anchor(site_url('menu/read/$1'),'Read')." | ".anchor(site_url('menu/update/$1'),'Update')." | ".anchor(site_url('menu/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    // get data surve
    function get_surve($data)
    {   
        // echo count(array_filter($data));
        
        // var_dump(array_filter($data));
        $jumlah_fileter = count(array_filter($data)) - 1;
        //echo $jumlah_fileter;
        $this->db->select('menu.nama,menu.img,menu.harga, count(menu.id) as menu_id');
        $this->db->from('menu');
        $this->db->join('menu_parameter', 'menu.id = menu_parameter.id_menu');
        foreach($data as $key => $value){
            if(isset($value)){
                $this->db->or_where('menu_parameter.keterangan',$value);
            }
        } 
        $this->db->group_by('menu.id');
        $this->db->having("menu_id >'".$jumlah_fileter."'");
        return $this->db->get()->result();
        foreach($data as $key => $value){
            if(isset($value)){
                $this->db->or_where('menu_parameter.keterangan',$value);
            }
        } 
        $this->db->group_by('menu.id');
        return $this->db->get()->result();
    }


    function get_kategori($kategori)
    {   $this->db->select('*');
        $this->db->from('menu');
        $this->db->join('stok', 'menu.id = stok.id_menu');
        $this->db->where('id_jenis', $kategori);
        $this->db->where('stok > ', '0');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_jenis', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('img', $q);
	$this->db->or_like('harga', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_jenis', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('img', $q);
	$this->db->or_like('harga', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Menu_model.php */
/* Location: ./application/models/Menu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-13 15:59:33 */
/* http://harviacode.com */