<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Menu_parameter_model extends CI_Model
{

    public $table = 'menu_parameter';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('menu_parameter.id,menu.nama,jenis_parameter.parameter as jenis,keterangan');
        $this->datatables->from('menu_parameter');
        //add this line for join
        $this->datatables->join('menu', 'menu_parameter.id_menu = menu.id');
        $this->datatables->join('parameter', 'menu_parameter.id_parameter = parameter.id');
        $this->datatables->join('jenis_parameter', 'parameter.id_jenis  = jenis_parameter.id');
        $this->datatables->add_column('action', anchor(site_url('menu_parameter/read/$1'),'Read')." | ".anchor(site_url('menu_parameter/update/$1'),'Update')." | ".anchor(site_url('menu_parameter/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_menu', $q);
	$this->db->or_like('id_parameter', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_menu', $q);
	$this->db->or_like('id_parameter', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Menu_parameter_model.php */
/* Location: ./application/models/Menu_parameter_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-13 15:56:08 */
/* http://harviacode.com */